- name: Запуск сервера мониторинга через Docker Compose
  hosts: server

  tasks:
    - name: 1. Создание директории для конфигурации Prometheus
      file:
        path: /tmp/prometheus_temp
        state: directory
        mode: '0755'

    - name: 2. Генерация конфигурации prometheus.yml из шаблона
      template:
        src: prometheus.yml.j2 # Берет файл на локальной машине
        dest: /tmp/prometheus_temp/prometheus.yml  # Копирует на удаленный сервер
      register: prometheus_config

    - name: 3. Копирование docker-compose.yml на сервер
      copy:
        src: docker-compose.yml
        dest: /tmp/prometheus_temp/docker-compose.yml

    - name: Сброс SSH-соединения для обновления групп
      meta: reset_connection

    - name: testing debug
      ansible.builtin.debug:
        msg:
        - "Пользователь: {{ ansible_user }}"

    - name:
      community.docker.docker_compose_v2:
        project_src: /tmp/prometheus_temp/
        state: present

- name: Развертывание Docker контейнера на агенте
  hosts: agent

  tasks:
# !!! Перед запуском установить коллекцию community.docker командой:
# ansible-galaxy collection install community.docker
    - name: 1. Запуск контейнера Node Exporter
      community.docker.docker_container:
        name: node-exporter
        image: prom/node-exporter:latest
        state: started
        restart_policy: unless-stopped
        network_mode: host
        pid_mode: host
        volumes:
          - /:/host:ro,rslave
        command:
          - --path.rootfs=/host